version: "3.8"
services:
  harvi_api:
    container_name: harvi_api
    build:
      context: .
      dockerfile: ./docker/php/Dockerfile
    expose:
      - 9000
    volumes:
      - .:/usr/src/app
      - ./public:/usr/src/app/public
    # depends_on:
    #   - harvi_db
    networks:
      - app_network

  harvi_nginx:
    container_name: harvi_nginx
    build:
      context: .
      dockerfile: ./docker/nginx/Dockerfile
    volumes:
    - ./public:/usr/src/app/public
    ports:
      - 8000:80
    depends_on:
      - harvi_api
    environment:
      NGINX_FPM_HOST: harvi_api
      NGINX_ROOT: /usr/src/app/public
    networks:
      - app_network

  harvi_db:
    container_name: harvi_db
    image: mysql:8.0.20
    restart: always
    volumes:
      - ./storage/db-data:/var/lib/mysql
    ports:
      - 3306:3306
    environment:
      MYSQL_DATABASE: sister_sweepers
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: root
      MYSQL_PASSWORD: root
    networks:
      - app_network

  # harvi_redis:
  #   container_name: harvi_redis
  #   image: redis:latest
  #   ports:
  #     - 6379:6379
  #   networks:
  #     - app_network

networks:
  app_network:
    driver: bridge
